 const allCoursesAndSpecializationsUG = [
    {
      course: "B.Tech",
      specializations: [
        { id: 1, label: "Agriculture" },
        { id: 2, label: "Automobile" },
        { id: 3, label: "Aviation" },
        { id: 4, label: "Bio-Chemistry/Bio-Technology" },
        { id: 5, label: "Biomedical" },
        { id: 6, label: "Ceramics" },
        { id: 7, label: "Chemical" },
        { id: 8, label: "Civil" },
        { id: 9, label: "Computers" },
        { id: 10, label: "Electrical" },
        { id: 11, label: "Electronics/Telecommunication" },
        { id: 12, label: "Energy" },
        { id: 13, label: "Environmental" },
        { id: 14, label: "Instrumentation" },
        { id: 15, label: "Marine" },
        { id: 16, label: "Mechanical" },
        { id: 17, label: "Metallurgy" },
        { id: 18, label: "Mineral" },
        { id: 19, label: "Mining" },
        { id: 20, label: "Nuclear" },
        { id: 21, label: "Paint/Oil" },
        { id: 22, label: "Petroleum" },
        { id: 23, label: "Plastics" },
        { id: 24, label: "Production/Industrial" },
        { id: 25, label: "Textile" },
        { id: 221, label: "Electrical and Electronics" },
        { id: 223, label: "Information Technology" },
      ],
    },
    {
      course: "B.Com",
      specializations: [{ id: 1, label: "Commerce" }],
    },
    {
      course: "B.Sc",
      specializations: [
        { id: 1, label: "Agriculture" },
        { id: 2, label: "Anthropology" },
        { id: 3, label: "Bio-Chemistry" },
        { id: 4, label: "Biology" },
        { id: 5, label: "Botany" },
        { id: 6, label: "Chemistry" },
        { id: 7, label: "Computers" },
        { id: 8, label: "Dairy Technology" },
        { id: 9, label: "Electronics" },
        { id: 10, label: "Environmental Science" },
        { id: 11, label: "Food Technology" },
        { id: 20, label: "General" },
        { id: 12, label: "Geology" },
        { id: 13, label: "Home Science" },
        { id: 22, label: "Hospitality and Hotel Management" },
        { id: 14, label: "Maths" },
        { id: 15, label: "Microbiology" },
        { id: 16, label: "Nursing" },
        { id: 23, label: "Optometry" },
        { id: 17, label: "Physics" },
        { id: 18, label: "Statistics" },
        { id: 19, label: "Zoology" },
      ],
    },
    {
      course: "B.A",
      specializations: [
        { id: 1, label: "Arts&Humanities" },
        { id: 2, label: "Communication" },
        { id: 3, label: "Economics" },
        { id: 4, label: "English" },
        { id: 5, label: "Film" },
        { id: 6, label: "Fine Arts" },
        { id: 7, label: "Hindi" },
        { id: 8, label: "History" },
        { id: 20, label: "Hotel Management" },
        { id: 9, label: "Journalism" },
        { id: 10, label: "Maths" },
        { id: 11, label: "Pass Course" },
        { id: 12, label: "Political Science" },
        { id: 13, label: "PR/Advertising" },
        { id: 14, label: "Psychology" },
        { id: 15, label: "Sanskrit" },
        { id: 16, label: "Sociology" },
        { id: 17, label: "Statistics" },
        { id: 18, label: "Vocational Course" },
      ],
    },
    {
      course: "Diploma",
      specializations: [
        { id: 1, label: "Architecture" },
        { id: 2, label: "Chemical" },
        { id: 3, label: "Civil" },
        { id: 4, label: "Computers" },
        { id: 5, label: "Electrical" },
        { id: 6, label: "Electronics/Telecommunication" },
        { id: 7, label: "Engineering" },
        { id: 8, label: "Export/Import" },
        { id: 9, label: "Fashion Designing/Other Designing" },
        { id: 10, label: "Graphic/ Web Designing" },
        { id: 11, label: "Hotel Management" },
        { id: 12, label: "Insurance" },
        { id: 13, label: "Management" },
        { id: 14, label: "Mechanical" },
        { id: 15, label: "Tourism" },
        { id: 16, label: "Visual Arts" },
        { id: 17, label: "Vocational Course" },
      ],
    },
    {
      course: "B.Arch",
      specializations: [{ id: 1, label: "Architecture" }],
    },
    {
      course: "B.B.A /B.M.S",
      specializations: [{ id: 1, label: "Management" }],
    },
    {
      course: "B.Des",
      specializations: [
        { id: 2, label: "Animation Film Design" },
        { id: 3, label: "Ceramic & Glass Design" },
        { id: 4, label: "Exhibition Design" },
        { id: 5, label: "Film and Video Communication" },
        { id: 7, label: "Furniture Design" },
        { id: 9, label: "Graphic Design" },
        { id: 8, label: "Product Design" },
        { id: 6, label: "Textile Design" },
      ],
    },
    {
      course: "B.Ed",
      specializations: [{ id: 1, label: "Education" }],
    },
    {
      course: "B.El.Ed",
      specializations: [{ id: 1, label: "Elementary Education" }],
    },
    {
      course: "B.P.Ed",
      specializations: [{ id: 1, label: "Physical Education" }],
    },
    {
      course: "B.Pharma",
      specializations: [{ id: 1, label: "Pharmacy" }],
    },
    {
      course: "B.U.M.S",
      specializations: [{ id: 1, label: "Unani Medicine" }],
    },
    {
      course: "BAMS",
      specializations: [{ id: 1, label: "Ayurveda" }],
    },
    {
      course: "BCA",
      specializations: [{ id: 1, label: "Computers" }],
    },
    {
      course: "BDS",
      specializations: [{ id: 1, label: "Dentistry" }],
    },
    {
      course: "BFA",
      specializations: [
        { id: 4, label: "Art History" },
        { id: 2, label: "Painting" },
        { id: 5, label: "Printmaking" },
        { id: 3, label: "Sculpture" },
        { id: 6, label: "Visual Communication" },
      ],
    },
    {
      course: "BHM",
      specializations: [{ id: 1, label: "Hotel Management" }],
    },
    {
      course: "BHMCT",
      specializations: [{ id: 1, label: "Hotel Management" }],
    },
    {
      course: "BHMS",
      specializations: [{ id: 1, label: "Homeopathy" }],
    },
    {
      course: "BVSC",
      specializations: [{ id: 1, label: "Veterinary Science" }],
    },
    {
      course: "LLB",
      specializations: [{ id: 1, label: "Law" }],
    },
    {
      course: "MBBS",
      specializations: [{ id: 1, label: "Medicine" }],
    },
  ];
  const allCoursesAndSpecializationsPG = [
    {
      course: "MBA/PGDM",
      specializations: [
        { id: 1, label: "Advertising/Mass Communication" },
        { id: 2, label: "Finance" },
        { id: 11, label: "Hospitality Management" },
        { id: 3, label: "HR/Industrial Relations" },
        { id: 4, label: "Information Technology" },
        { id: 5, label: "International Business" },
        { id: 6, label: "Marketing" },
        { id: 9, label: "Operations" },
        { id: 7, label: "Systems" },
      ],
    },
    {
      course: "M.Tech",
      specializations: [
        { id: 1, label: "Agriculture" },
        { id: 2, label: "Automobile" },
        { id: 3, label: "Aviation" },
        { id: 4, label: "Bio-Chemistry/Bio-Technology" },
        { id: 5, label: "Biomedical" },
        { id: 6, label: "Ceramics" },
        { id: 7, label: "Chemical" },
        { id: 8, label: "Civil" },
        { id: 9, label: "Computers" },
        { id: 10, label: "Electrical" },
        { id: 11, label: "Electronics/Telecommunication" },
        { id: 12, label: "Energy" },
        { id: 13, label: "Environmental" },
        { id: 14, label: "Instrumentation" },
        { id: 15, label: "Marine" },
        { id: 16, label: "Mechanical" },
        { id: 17, label: "Metallurgy" },
        { id: 18, label: "Mineral" },
        { id: 19, label: "Mining" },
        { id: 20, label: "Nuclear" },
        { id: 21, label: "Paint/Oil" },
        { id: 22, label: "Petroleum" },
        { id: 23, label: "Plastics" },
        { id: 24, label: "Production/Industrial" },
        { id: 25, label: "Textile" },
      ],
    },
    {
      course: "MS/M.Sc(Science)",
      specializations: [
        { id: 26, label: "Aerospace & Mechanical Engineering" },
        { id: 1, label: "Agriculture" },
        { id: 2, label: "Anthropology" },
        { id: 25, label: "Astronautical Engineering" },
        { id: 3, label: "Bio-Chemistry" },
        { id: 4, label: "Biology" },
        { id: 22, label: "Biotechnology" },
        { id: 5, label: "Botany" },
        { id: 27, label: "Chemical Engineering & Materials Science" },
        { id: 6, label: "Chemistry" },
        { id: 28, label: "Civil & Environmental Engineering" },
        { id: 7, label: "Computers" },
        { id: 32, label: "Cyber Security Engineering" },
        { id: 8, label: "Dairy Technology" },
        { id: 33, label: "Data Informatics" },
        { id: 29, label: "Electrical Engineering" },
        { id: 9, label: "Electronics" },
        { id: 37, label: "Electronics & Embedded Technology" },
        { id: 10, label: "Environmental science" },
        { id: 11, label: "Food Technology" },
        { id: 12, label: "Geology" },
        { id: 13, label: "Home science" },
        { id: 39, label: "Hospitality Administration" },
        { id: 30, label: "Industrial & Systems Engineering" },
        { id: 36, label: "Marine Engineering" },
        { id: 14, label: "Maths" },
        { id: 35, label: "Mechanical Engineering" },
        { id: 38, label: "Mechatronics" },
        { id: 15, label: "Microbiology" },
        { id: 16, label: "Nursing" },
        { id: 24, label: "Optometry" },
        { id: 23, label: "Organic Chemistry" },
        { id: 31, label: "Petroleum Engineering" },
        { id: 17, label: "Physics" },
        { id: 18, label: "Statistics" },
        { id: 34, label: "Systems Architecting and Engineering" },
        { id: 21, label: "Veterinary Science" },
        { id: 19, label: "Zoology" },
      ],
    },
    {
      course: "MCA",
      specializations: [{ id: 1, label: "Computers" }],
    },
    {
      course: "M.Com",
      specializations: [{ id: 1, label: "Commerce" }],
    },
    {
      course: "PG Diploma",
      specializations: [
        { id: 1, label: "Chemical" },
        { id: 2, label: "Civil" },
        { id: 3, label: "Computers" },
        { id: 4, label: "Electrical" },
        { id: 5, label: "Electronics" },
        { id: 6, label: "Mechanical" },
      ],
    },
    {
      course: "M.A",
      specializations: [
        { id: 1, label: "Anthropology" },
        { id: 2, label: "Arts & Humanities" },
        { id: 3, label: "Communication" },
        { id: 4, label: "Economics" },
        { id: 5, label: "English" },
        { id: 6, label: "Film" },
        { id: 7, label: "Fine Arts" },
        { id: 8, label: "Hindi" },
        { id: 9, label: "History" },
        { id: 10, label: "Journalism" },
        { id: 11, label: "Maths" },
        { id: 12, label: "Political Science" },
        { id: 13, label: "PR/ Advertising" },
        { id: 14, label: "Psychology" },
        { id: 15, label: "Sanskrit" },
        { id: 16, label: "Sociology" },
        { id: 17, label: "Statistics" },
      ],
    },
    {
      course: "CA",
      specializations: [
        { id: 1, label: "CA" },
        { id: 3, label: "First Attempt" },
        { id: 2, label: "Pursuing" },
        { id: 4, label: "Second Attempt" },
      ],
    },
    {
      course: "CS",
      specializations: [{ id: 1, label: "CS" }],
    },
    {
      course: "DM",
      specializations: [
        { id: 16, label: "Cardiac -Anaes." },
        { id: 10, label: "Cardiology" },
        { id: 21, label: "Child & Adolescent Psychiatry" },
        { id: 3, label: "Clinical Haematology" },
        { id: 14, label: "Clinical Immunology" },
        { id: 2, label: "Clinical Pharmacology" },
        { id: 35, label: "Critical Care Medicine" },
        { id: 13, label: "Endocrinology" },
        { id: 9, label: "Gastroenterology" },
        { id: 31, label: "Geriatric Mental Health" },
        { id: 17, label: "Haematology Pathology" },
        { id: 19, label: "Hepatology" },
        { id: 20, label: "Immunology" },
        { id: 33, label: "Infectious Diseases" },
        { id: 18, label: "Medical Genetics" },
        { id: 7, label: "Neonatology" },
        { id: 6, label: "Nephrology" },
        { id: 25, label: "Neuro Anaesthesia" },
        { id: 5, label: "Neuro Radiology" },
        { id: 11, label: "Neurology" },
        { id: 8, label: "Oncology" },
        { id: 34, label: "Organ Transplant Anaesthesia & Critical Care" },
        { id: 24, label: "Pediatric Anaesthesia" },
        { id: 23, label: "Pediatric Cardiology" },
        { id: 22, label: "Pediatric Gastroenterology" },
        { id: 32, label: "Pediatric Hepatology" },
        { id: 26, label: "Pediatric Nephrology" },
        { id: 30, label: "Pediatric Oncology" },
        { id: 15, label: "Pulmonary Med. & Critical Care Med." },
        { id: 4, label: "Pulmonary Medicine" },
        { id: 27, label: "Reproductive Medicine" },
        { id: 12, label: "Rheumatology" },
        { id: 29, label: "Virology" },
      ],
    },
    {
      course: "ICWA (CMA)",
      specializations: [{ id: 1, label: "ICWA (CMA)" }],
    },
    {
      course: "Integrated PG",
      specializations: [
        { id: 1, label: "Journalism / Mass Communication" },
        { id: 2, label: "Management" },
        { id: 3, label: "PR/ Advertising" },
        { id: 4, label: "Tourism" },
      ],
    },
    {
      course: "LLM",
      specializations: [{ id: 1, label: "Law" }],
    },
    {
      course: "M.Arch",
      specializations: [{ id: 1, label: "Architecture" }],
    },
    {
      course: "M.Ch",
      specializations: [
        { id: 9, label: "Burns & Plastic Surgery" },
        { id: 14, label: "Cardio Thoracic and Vascular Surgery" },
        { id: 13, label: "Cardio Thoracic Surgery" },
        { id: 10, label: "Endocrine Surgery" },
        { id: 3, label: "Gynaecological Oncology" },
        { id: 8, label: "Hand & Micro Surgery" },
        { id: 2, label: "Hand Surgery" },
        { id: 6, label: "Hepato Pancreato Biliary Surgery" },
        { id: 15, label: "Neuro Surgery" },
        { id: 11, label: "Oncology" },
        { id: 4, label: "Pediatric Cardio-Thoracic Vascular Surgery" },
        { id: 16, label: "Pediatric Surgery" },
        { id: 5, label: "Plastic & Reconstructive Surgery" },
        { id: 17, label: "Plastic Surgery" },
        { id: 18, label: "Surgical Gastroenterology/G.I. Surgery" },
        { id: 19, label: "Surgical Oncology" },
        { id: 20, label: "Thoracic Surgery" },
        { id: 21, label: "Urology" },
        { id: 7, label: "Urology/Genito -Urinary Surgery" },
        { id: 12, label: "Vascular Surgery" },
      ],
    },
    {
      course: "M.Des",
      specializations: [
        { id: 2, label: "Animation Film Design" },
        { id: 3, label: "Apparel Design" },
        { id: 4, label: "Ceramic & Glass Design" },
        { id: 5, label: "Design For Retail Experience" },
        { id: 6, label: "Digital Game Design" },
        { id: 7, label: "Film and Video Communication" },
        { id: 8, label: "Furniture Design" },
        { id: 9, label: "Graphic Design" },
        { id: 10, label: "Information Design" },
        { id: 11, label: "Interaction Design" },
        { id: 12, label: "Lifestyle Accessory Design" },
        { id: 13, label: "New Media Design" },
        { id: 14, label: "Photography Design" },
        { id: 15, label: "Product Design" },
        { id: 16, label: "Strategic Design Management" },
        { id: 17, label: "Textile Design" },
        { id: 18, label: "Toy & Game Design" },
        { id: 19, label: "Transportation & Automobile Design" },
        { id: 20, label: "Universal Design" },
      ],
    },
    {
      course: "M.Ed",
      specializations: [{ id: 1, label: "Education" }],
    },
    {
      course: "M.Pharma",
      specializations: [{ id: 1, label: "Pharmacy" }],
    },
    {
      course: "MCM",
      specializations: [{ id: 1, label: "Computers and Management" }],
    },
    {
      course: "MDS",
      specializations: [{ id: 2, label: "Dentistry" }],
    },
    {
      course: "Medical-MS/MD",
      specializations: [
        { id: 46, label: "Anaesthesiology" },
        { id: 47, label: "Anatomy" },
        { id: 28, label: "Aviation Medicine/Aerospace Medicine" },
        { id: 23, label: "Ayurveda" },
        { id: 64, label: "Bio-Chemistry" },
        { id: 66, label: "Bio-Physics" },
        {
          id: 34,
          label: "Blood Banking & Immuno. Haem./Imm. Haem. & Blood Trans.",
        },
        { id: 1, label: "Cardiology" },
        { id: 38, label: "CCM" },
        { id: 2, label: "Dermatology" },
        { id: 44, label: "Emergency Medicine" },
        { id: 3, label: "ENT" },
        { id: 48, label: "Forensic Medicine/Forensic Medicine & Toxicology" },
        { id: 4, label: "General Practitioner" },
        { id: 68, label: "General Surgery" },
        { id: 50, label: "Geriatrics" },
        { id: 5, label: "Gyneocology" },
        { id: 52, label: "Health Administration" },
        { id: 6, label: "Hepatology" },
        { id: 51, label: "Hospital Administration" },
        { id: 7, label: "Immunology" },
        { id: 53, label: "Lab Medicine" },
        { id: 36, label: "Maternity & Child Health" },
        { id: 31, label: "Medical Genetics" },
        { id: 8, label: "Microbiology" },
        { id: 9, label: "Neonatal" },
        { id: 10, label: "Nephrology" },
        { id: 69, label: "Neuro Surgery" },
        { id: 54, label: "Nuclear Medicine" },
        { id: 12, label: "Obstetrics" },
        { id: 13, label: "Oncology" },
        { id: 14, label: "Ophthalmology" },
        { id: 15, label: "Orthopaedic" },
        { id: 39, label: "P.S.M" },
        { id: 32, label: "Palliative Medicine" },
        { id: 16, label: "Pathology" },
        { id: 17, label: "Pediatrics" },
        { id: 58, label: "Pharmacology" },
        { id: 60, label: "Physical Medicine & Rehabilitation" },
        { id: 18, label: "Psychiatry" },
        { id: 19, label: "Psychology" },
        { id: 33, label: "Public Health (Epidemiology)" },
        { id: 37, label: "Pulmonary Medicine" },
        { id: 45, label: "R&D" },
        { id: 20, label: "Radiology" },
        { id: 61, label: "Radiotherapy" },
        { id: 21, label: "Rheumatology" },
        { id: 62, label: "Social & Preventive Medicine / Community Medicine" },
        { id: 25, label: "Sports Medicine" },
        { id: 24, label: "Thoracic Medicine" },
        { id: 70, label: "Traumatology and Surgery" },
        { id: 35, label: "Tropical Medicine" },
        {
          id: 29,
          label: "Tuberculosis & Respiratory Diseases / Pulmonary Medicine",
        },
        { id: 65, label: "Unani" },
        { id: 11, label: "Urology" },
        { id: 63, label: "Venereology" },
      ],
    },
    {
      course: "MFA",
      specializations: [
        { id: 3, label: "Printmaking" },
        { id: 2, label: "Sculpture" },
        { id: 4, label: "Visual Communication" },
      ],
    },
    {
      course: "MVSC",
      specializations: [{ id: 1, label: "Veterinary Science" }],
    },
  ];
